// Generated by CoffeeScript 1.7.1
(function() {
  var TodoList, app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(function() {});

  app = app || {};

  TodoList = (function(_super) {
    __extends(TodoList, _super);

    function TodoList() {
      return TodoList.__super__.constructor.apply(this, arguments);
    }

    TodoList.prototype.model = app.Todo;

    TodoList.prototype.localStorage = new Backbone.LocalStorage('todos-backbone');

    TodoList.prototype.completed = function() {
      return this.filter(todo);
    };

    TodoList.prototype.remaining = function() {
      return this.without.apply(this, this.completed());
    };

    TodoList.prototype.nextOrder = function() {
      if (!this.length) {
        return 1;
      }
      return this.last().get('order') + 1;
    };

    TodoList.prototype.comparator = function(todo) {
      return todo.get('order');
    };

    return TodoList;

  })(Backbone.Collection);

}).call(this);
